% figure_solve_time_cdf.m
% Figure solve_time_cdf in Section VI-A.1: empirical CDF of solve times.

clc; close all;

% NatComm figure formatting: LaTeX interpreter, 5–7 pt text
set(groot, 'DefaultAxesTickLabelInterpreter', 'latex');
set(groot, 'DefaultTextInterpreter',          'latex');
set(groot, 'DefaultLegendInterpreter',        'latex');

set(groot, 'DefaultAxesFontName',   'Helvetica');
set(groot, 'DefaultTextFontName',   'Helvetica');
set(groot, 'DefaultLegendFontName', 'Helvetica');

set(groot, 'DefaultAxesFontSize',   9);
set(groot, 'DefaultTextFontSize',   9);
set(groot, 'DefaultLegendFontSize', 9);

% Locate the project root from this file's own location, so the script runs
% from any checkout.
projectRoot = fileparts(fileparts(mfilename('fullpath')));

initFile = fullfile(projectRoot, 'initProjectPaths.m');
if ~isfile(initFile)
    error('Cannot find initProjectPaths.m in:\n%s', projectRoot);
end

% Bootstrap the project path.
addpath(projectRoot);
rootDir = initProjectPaths(mfilename('fullpath'));
resultsDir = ensureResultsDir(rootDir);
figuresDir = fullfile(resultsDir, 'Figures');

if ~exist(figuresDir, 'dir')
    mkdir(figuresDir);
end

latestFile = findLatestResultFile( ...
    fullfile(rootDir, 'results', ...
    'Results_nominal_wltc_*.mat'), ...
    'Run mainSimulationRunners/run_nominal_wltc.m first.');

data = load(latestFile);
fprintf('Loaded %s\n', latestFile);

if isfield(data, 'cfg') && isfield(data.cfg, 'timeLimit')
    t_op_lim = 1e3 * data.cfg.timeLimit;  % ms
else
    t_op_lim = 1e3;                      % ms
end

R = data.Results;

active_A = ~R.A.log.rest_skip;
active_D = ~R.D.log.rest_skip;

% Convert solver times from seconds to milliseconds.
sw_A = 1e3 * R.A.log.solver_time(active_A);
sw_A = sw_A(isfinite(sw_A));

sw_D = 1e3 * R.D.log.solver_time(active_D);
sw_D = sw_D(isfinite(sw_D));

t_grid = linspace(0, 1500, 2000);  % ms

cdf_A = mean(sw_A(:) <= t_grid, 1) * 100;
cdf_D = mean(sw_D(:) <= t_grid, 1) * 100;

pct_A_at_limit = mean(sw_A >= t_op_lim) * 100;

t_50_A  = median(sw_A);
t_50_D  = median(sw_D);
t_p95_A = prctile(sw_A, 95);
t_p95_D = prctile(sw_D, 95);

fprintf('A: t_50=%.1f ms  t_95=%.1f ms  at_limit=%.1f%%\n', ...
    t_50_A, t_p95_A, pct_A_at_limit);

fprintf('D: t_50=%.1f ms  t_95=%.1f ms  max=%.1f ms\n', ...
    t_50_D, t_p95_D, max(sw_D));

% IEEEtran one-column figure dimensions (3.375 in = 8.573 cm)
paperWidth  = 8.573;   % cm
paperHeight = 6;     % cm — adjust if needed

fig = figure( ...
    'Color',    'w', ...
    'Units',    'centimeters', ...
    'Position', [2 2 paperWidth paperHeight]);

ax = axes('Parent', fig);

col_A = [0.00 0.45 0.70];
col_D = [0.80 0.40 0.00];

lw = 1.4;
fs = 9;

hold(ax, 'on');

h_A = plot(ax, t_grid, cdf_A, '-', ...
    'Color', col_A, ...
    'LineWidth', lw);

h_D = plot(ax, t_grid, cdf_D, '--', ...
    'Color', col_D, ...
    'LineWidth', lw);

plot(ax, [t_op_lim t_op_lim], [0 100], ':', ...
    'Color', [0.3 0.3 0.3], ...
    'LineWidth', 1.0);

text(ax, t_op_lim - 10, 50, '$t_{\mathrm{lim}}^{\mathrm{op}}$', ...
    'HorizontalAlignment', 'right', ...
    'Interpreter',         'latex', ...
    'FontSize',            fs, ...
    'Color',               [0.3 0.3 0.3]);

marker_sz = 6;

cdf_50_A  = interp1(t_grid, cdf_A, t_50_A);
cdf_p95_A = interp1(t_grid, cdf_A, t_p95_A);
cdf_50_D  = interp1(t_grid, cdf_D, t_50_D);
cdf_p95_D = interp1(t_grid, cdf_D, t_p95_D);

plot(ax, t_50_A, cdf_50_A, 'o', ...
    'Color',           col_A, ...
    'MarkerFaceColor', col_A, ...
    'MarkerSize',      marker_sz);

plot(ax, t_p95_A, cdf_p95_A, 's', ...
    'Color',           col_A, ...
    'MarkerFaceColor', col_A, ...
    'MarkerSize',      marker_sz);

plot(ax, t_50_D, cdf_50_D, 'o', ...
    'Color',           col_D, ...
    'MarkerFaceColor', col_D, ...
    'MarkerSize',      marker_sz);

plot(ax, t_p95_D, cdf_p95_D, 's', ...
    'Color',           col_D, ...
    'MarkerFaceColor', col_D, ...
    'MarkerSize',      marker_sz);

% Show only the symbol for t_50.
text(ax, t_50_A + 20, cdf_50_A - 2, '$t_{50}$', ...
    'Color',       col_A, ...
    'FontSize',    fs, ...
    'Interpreter', 'latex');

text(ax, t_50_D + 10, cdf_50_D + 8, '$t_{50}$', ...
    'Color',       col_D, ...
    'FontSize',    fs, ...
    'Interpreter', 'latex');

% Show the numerical value for t_p95.
text(ax, t_p95_A + 20, cdf_p95_A - 2, ...
    sprintf('$t_{\\mathrm{95}}=%.0f\\,\\mathrm{ms}$', t_p95_A), ...
    'Color',               col_A, ...
    'FontSize',            fs, ...
    'VerticalAlignment',   'top', ...
    'HorizontalAlignment', 'left', ...
    'Interpreter',         'latex');

text(ax, t_p95_D + 20, cdf_p95_D - 1, ...
    sprintf('$t_{\\mathrm{95}}=%.0f\\,\\mathrm{ms}$', t_p95_D), ...
    'Color',               col_D, ...
    'FontSize',            fs, ...
    'VerticalAlignment',   'top', ...
    'HorizontalAlignment', 'left', ...
    'Interpreter',         'latex');

xlim(ax, [0 1500]);
ylim(ax, [0 100]);

set(ax, ...
    'XTick', 0:250:1500, ...
    'YTick', 0:20:100);

xlabel(ax, '$\mathrm{Solver\ time}\ t_s\ [\mathrm{ms}]$', ...
    'Interpreter', 'latex', ...
    'FontSize',    fs);

ylabel(ax, '$\mathrm{Cumulative\ fraction}\ [\%]$', ...
    'Interpreter', 'latex', ...
    'FontSize',    fs);

legend(ax, [h_A h_D], ...
    {'$\mathrm{Baseline}$', '$\mathrm{Proposed}$'}, ...
    'Location',    'southeast', ...
    'FontSize',    fs, ...
    'Interpreter', 'latex');

legend(ax, 'boxoff');

set(ax, ...
    'FontSize',             fs, ...
    'TickLabelInterpreter', 'latex', ...
    'LineWidth',            0.6, ...
    'Box',                  'on');

grid(ax, 'on');

set(ax, ...
    'GridAlpha',     0.2, ...
    'GridLineStyle', ':');

drawnow;

set(fig, ...
    'Units',             'centimeters', ...
    'Position',          [2 2 paperWidth paperHeight], ...
    'PaperUnits',        'centimeters', ...
    'PaperSize',         [paperWidth paperHeight], ...
    'PaperPosition',     [0 0 paperWidth paperHeight], ...
    'PaperPositionMode', 'manual', ...
    'Color',             'w');

outFile = fullfile(figuresDir, 'figure_solve_time_cdf');

exportgraphics(fig, [outFile '.pdf'], ...
    'ContentType',     'vector', ...
    'BackgroundColor', 'white');

exportgraphics(fig, [outFile '.eps'], ...
    'ContentType',     'vector', ...
    'BackgroundColor', 'white');

fprintf('Saved figure_solve_time_cdf.eps and .pdf\n');